// Generated by CoffeeScript 1.6.3
(function() {
  var IframeProxy, body, ctFrame, doc, getConf, getReq, onBind, scriptNode, scripts, window;

  window = this;

  doc = window.document;

  body = doc.body;

  ctFrame = function() {
    var el;
    el = doc.createElement('iframe');
    el.style.display = 'none';
    el.name = 'qPay-proxy';
    return el;
  };

  onBind = function(evType, callback) {
    if (doc.addEventListener) {
      window.addEventListener(evType, callback, false);
      return;
    }
    window.attachEvent("on" + evType, callback);
  };

  getReq = function(param) {
    var regArr, rgx;
    rgx = new RegExp('(^|&)' + name + '=([^&]*)(&|$)', 'i');
    regArr = window.location.search.substr(1).match(rgx);
    if (regArr !== null) {
      return unescape(regArr[2]);
    } else {
      return null;
    }
  };

  scripts = doc.getElementsByTagName('script');

  scriptNode = scripts[scripts.length - 1];

  getConf = function(param) {
    var pm;
    pm = scriptNode.getAttribute(param);
    if (pm) {
      return pm;
    } else {
      return getReq(param);
    }
  };

  IframeProxy = function() {
    this.height = 0;
    this.frameId = getConf('data-frameid');
    this.time = getConf('data-time');
    this.proxyPath = getConf('data-proxy');
    this.proxyIframe = ctFrame();
  };

  IframeProxy.prototype = {
    init: function() {
      var self, _init;
      self = this;
      _init = function() {
        body.appendChild(self.proxyIframe);
        self.reSetHeight();
        if (self.time) {
          self.time = self.time < 500 ? 500 : self.time;
          return window.setInterval(function() {
            if (body.offsetHeight !== self.height) {
              return self.reSetHeight();
            }
          }, self.time);
        }
      };
      return onBind('load', _init);
    },
    /*
    	* 重设高度
    */

    reSetHeight: function() {
      var self;
      self = this;
      self.height = body.offsetHeight;
      self.proxyIframe.src = self.proxyPath + '?data-frameid=' + self.frameId + '&data-frameheight=' + (self.height + 40);
    }
  };

  (new IframeProxy()).init();

}).call(this);
